[package]
name = "practical-astronomy-rust-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
practical-astronomy-rust = { version = "0.2.0", path = "../practical-astronomy-rust" }
